<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-08-03 19:54

=======
# Generated by Django 5.2.4 on 2025-08-09 20:22

import django.db.models.deletion
from django.conf import settings
>>>>>>> 3f4b7bd0cbafc8bb7999aa9dfdbadf809cab1ba6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = []
=======
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
>>>>>>> 3f4b7bd0cbafc8bb7999aa9dfdbadf809cab1ba6

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "resources",
<<<<<<< HEAD
                    models.FileField(blank=True, null=True, upload_to="resources/"),
=======
                    models.FileField(
                        blank=True, null=True, upload_to="resources/%Y/%m/%d/"
                    ),
>>>>>>> 3f4b7bd0cbafc8bb7999aa9dfdbadf809cab1ba6
                ),
                ("draft", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
            ],
=======
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="forum.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
>>>>>>> 3f4b7bd0cbafc8bb7999aa9dfdbadf809cab1ba6
        ),
    ]
