# Generated by Django 5.2.4 on 2025-08-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="resources",
            field=models.FileField(blank=True, null=True, upload_to="resources/"),
        ),
    ]
