# Generated by Django 5.2.4 on 2025-08-16 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Sube una imagen destacada (JPG, PNG, WEBP). Recomendado: 1200x630 px.",
                null=True,
                upload_to="posts/images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="Imagen destacada",
            ),
        ),
    ]
